function [Quota, Rhokgm3] = importfileRhoQuota(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  [QUOTA, RHOKGM3] = IMPORTFILE1(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as column
%  vectors.
%
%  [QUOTA, RHOKGM3] = IMPORTFILE1(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  [Quota, Rhokgm3] = importfile1("/Users/giuseppegiaquinto/OneDrive/M53/II anno - I semestre/ipersonica/esercizi/USSA76.dat", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 14-Oct-2021 00:11:12

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 6);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Quota", "Var2", "Var3", "Rhokgm3", "Var5", "Var6"];
opts.SelectedVariableNames = ["Quota", "Rhokgm3"];
opts.VariableTypes = ["double", "string", "string", "double", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var2", "Var3", "Var5", "Var6"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var2", "Var3", "Var5", "Var6"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["Quota", "Rhokgm3"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["Quota", "Rhokgm3"], "DecimalSeparator", ",");
opts = setvaropts(opts, ["Quota", "Rhokgm3"], "ThousandsSeparator", ".");

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
Quota = tbl.Quota;
Rhokgm3 = tbl.Rhokgm3;
end